name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        dotnet: ["5.0"]
        os: ['ubuntu-latest','macos-latest', 'windows-latest']
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: actions/setup-dotnet@main
                
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
            dotnet --info
            dotnet build "rpgsaga/RpgSaga.sln"
            dotnet test "rpgsaga/RpgSaga.sln"
